# analysis and save the results
library(tidyverse)
load("rda/murders.rda")

murders %>% mutate(abb = reorder(abb, rate)) %>%
  ggplot(aes(abb, rate)) +
  geom_bar(width = 0.5, stat = "identity", color = "black") +
  coord_flip() 

# save a plot generated by ggplot2 to a dir called "figs"
# the format is "foldername/name.type of image"
ggsave("figs/barplot.png")

